Ext.define('Base.model.UlnDetails', {
	extend: 'Ext.data.Model',
	fields: [
		{name: "PlanId"},
		{name: "ReqId"},
		{name: "ULNId"},
		{name: "SvcULN"},		
		{name: 'CreateDate'},
		{name: "CreateUserId"},
		{name: 'UpdateDate'},
		{name: "WorkflowNodeId"},
		{name: "WorkflowNode"},
		{name: 'WorkflowDueDate'},
		{name: "RegAggId", type: 'int'},
		{name: "DualAggId", type: 'int'},
		{name: "ALD", type: 'auto'},
		{name: "ArmySourceCode"},
		{name: "ArrivalIndicatorCode"},
		{name: "Baseline"},
		{name: "BulkPOLVolume", type: 'float'},
		{name: "BulkVolume", type: 'float'},
		{name: "BulkWeight", type: 'float'},
		{name: "CINCValidation", type: 'int'},
		{name: "ComponentCode"},
		{name: "ContainerizedArea", type: 'float'},
		{name: "ContainerizedVolume", type: 'float'},
		{name: "ContainerizedWeight", type: 'float'},
		{name: "CRD", type: 'auto'},
		{name: "CriticalEmploymentIndicator"},
		{name: "DeploymentOrder"},
		{name: "DestinationDischargeConstraints"},
		{name: "DestinationGeolocationCode"},
		{name: "DestinationLoadConfiguration"},
		{name: "DestinationMeansCode"},
		{name: "DestinationModeCode"},
		{name: "DestinationName"},
		{name: "DestinationSourceCode"},
		{name: "DestinationOnCallIndicator"},
		{name: "EAD", type: 'auto'},
		{name: "ErrorCode"},
		{name: "ForceDescription"},
		{name: "ForceTrackingNumber"},
		{name: "FragCode"},
		{name: "GCC"},
		{name: "ILOCs", type: 'int'},
		{name: "InPlace"},
		{name: "JointRqmtCode"},
		{name: "LAD", type: 'auto'},
		{name: "Level2CargoUpdateIndicator"},
		{name: "MMCVolume", type: 'float'},
		{name: "MMCWeight", type: 'float'},
		{name: "NATVolume", type: 'float'},
		{name: "NATWeight", type: 'float'},
		{name: "NoncontainerizedVolume", type: 'float'},
		{name: "NSDABArea", type: 'float'},
		{name: "NSDABVolume", type: 'float'},
		{name: "NumberOfCargoCategories", type: 'int'},
		{name: "OriginGeolocationCode"},
		{name: "OriginName"},
		{name: "OtherArea", type: 'float'},
		{name: "OtherTransDate", type: 'int'},
		{name: "OtherTransStatusCode"},
		{name: "OtherVolume", type: 'float'},
		{name: "OUID"},
		{name: "OutsizeVolume", type: 'float'},
		{name: "OutsizeWeight", type: 'float'},
		{name: "OversizedVolume", type: 'float'},
		{name: "OversizedWeight", type: 'float'},
		{name: "OverOutVolume", type: 'float'},
		{name: "OverOutWeight", type: 'float'},
		{name: "PAX", type: 'int'},
		{name: "Personnel", type: 'int'},
		{name: "PIC"},
		{name: "PIFCode"},
		{name: "PIFDate", type: 'int'},
		{name: "POCDutyPhoneTx"},
		{name: "POCEmailTx"},
		{name: "POCEvePhoneTx"},
		{name: "POCName"},
		{name: "POCRankCode"},
		{name: "POCTx"},
		{name: "POCUntURLTx"},
		{name: "PODDischargeConstraints"},
		{name: "PODGeolocationCode"},
		{name: "PODLoadConfiguration"},
		{name: "PODMeansCode"},
		{name: "PODModeCode"},
		{name: "PODName"},
		{name: "PODOnCallIndicator"},
		{name: "PODPriorityAddOn"},
		{name: "PODPriorityForArrival"},
		{name: "PODSourceCode"},
		{name: "POEGeolocationCode"},
		{name: "POEMeansCode"},
		{name: "POEModeCode"},
		{name: "POEName"},
		{name: "POESourceCode"},
		{name: "PreviousPlanId"},
		{name: "PreviousULNId"},
		{name: "ProjectCode"},
		{name: "ProvidingOrgCode"},
		{name: "RDD", type: 'auto'},
		{name: "RDP", type: 'auto'},
		{name: "RequestForForcesIdentifier"},
		{name: "ReservedOne"},
		{name: "ReservedTwo"},
		{name: "ReservedThree"},
		{name: "ReservedFour"},
		{name: "RestructureOperationCode"},
		{name: "RestructureUpdateDate", type: 'int'},
		{name: "RLD", type: 'auto'},
		{name: "ServiceCode"},
		{name: "ServiceRsv"},
		{name: "SIC"},
		{name: "SplitCode"},
		{name: "SupportedCINCComponentVerificationIndicator", type: 'int'},
		{name: "SupportingCINCComponentVerificationIndicator", type: 'int'},
		{name: "SupportingCINCVerificationIndicator", type: 'int'},
		{name: "TotalArea", type: 'float'},
		{name: "TotalVolume", type: 'float'},
		{name: "TotalWeight", type: 'float'},
		{name: "TTAN"},
		{name: "TUCHADescription"},
		{name: "TUCHAStatus"},
		{name: "UIC"},
		{name: "parentUic"},
		{name: "UICInGSORTSIndicator"},
		{name: "ULC"},
		{name: "UlnFtnLineNumber", type: 'int'},
		{name: "UnitName"},
		{name: "USTCDate", type: 'int'},
		{name: "USTCStatus"},
		{name: "UTC"},
		{name: "ValidationCandidateIndicator", type: 'int'},
		{name: "VehicularArea", type: 'float'},
		{name: "VehicularVolume", type: 'float'},
		{name: "Version", type: 'int'}
	]
});
