package com.inalab.model;
import java.math.BigDecimal;
import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Long id;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.departmentname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date etldate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.departmentname
     *
     * @return the value of department.departmentname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.departmentname
     *
     * @param departmentname the value for department.departmentname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.createdate
     *
     * @return the value of department.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.createdate
     *
     * @param createdate the value for department.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.updatedate
     *
     * @return the value of department.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.updatedate
     *
     * @param updatedate the value for department.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.etldate
     *
     * @return the value of department.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getEtldate() {
        return etldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.etldate
     *
     * @param etldate the value for department.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setEtldate(Date etldate) {
        this.etldate = etldate;
    }
}