package com.inalab.model;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.userid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private BigDecimal userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.firstname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.lastname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.departmentid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private BigDecimal departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date etldate;

    private String activeind;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.userid
     *
     * @return the value of employee.userid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public BigDecimal getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.userid
     *
     * @param userid the value for employee.userid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.firstname
     *
     * @return the value of employee.firstname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.firstname
     *
     * @param firstname the value for employee.firstname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.lastname
     *
     * @return the value of employee.lastname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.lastname
     *
     * @param lastname the value for employee.lastname
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.departmentid
     *
     * @return the value of employee.departmentid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public BigDecimal getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.departmentid
     *
     * @param departmentid the value for employee.departmentid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setDepartmentid(BigDecimal departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.createdate
     *
     * @return the value of employee.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.createdate
     *
     * @param createdate the value for employee.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.updatedate
     *
     * @return the value of employee.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.updatedate
     *
     * @param updatedate the value for employee.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.etldate
     *
     * @return the value of employee.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getEtldate() {
        return etldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.etldate
     *
     * @param etldate the value for employee.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setEtldate(Date etldate) {
        this.etldate = etldate;
    }

	public String getActiveind() {
		
		if(StringUtils.isEmpty(activeind))
			return "Y";
		
		return activeind;
	}

	public void setActiveind(String activeind) {
		this.activeind = activeind;
	}
}