package com.inalab.model;

import java.math.BigDecimal;
import java.util.Date;

public class Kudos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kudos.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kudos.from_eid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private BigDecimal fromEid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kudos.to_eid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private BigDecimal toEid;

    private BigDecimal count;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kudos.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kudos.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kudos.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    private Date etldate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kudos.id
     *
     * @return the value of kudos.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kudos.id
     *
     * @param id the value for kudos.id
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kudos.from_eid
     *
     * @return the value of kudos.from_eid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public BigDecimal getFromEid() {
        return fromEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kudos.from_eid
     *
     * @param fromEid the value for kudos.from_eid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setFromEid(BigDecimal fromEid) {
        this.fromEid = fromEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kudos.to_eid
     *
     * @return the value of kudos.to_eid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public BigDecimal getToEid() {
        return toEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kudos.to_eid
     *
     * @param toEid the value for kudos.to_eid
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setToEid(BigDecimal toEid) {
        this.toEid = toEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kudos.createdate
     *
     * @return the value of kudos.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kudos.createdate
     *
     * @param createdate the value for kudos.createdate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kudos.updatedate
     *
     * @return the value of kudos.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kudos.updatedate
     *
     * @param updatedate the value for kudos.updatedate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kudos.etldate
     *
     * @return the value of kudos.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public Date getEtldate() {
        return etldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kudos.etldate
     *
     * @param etldate the value for kudos.etldate
     *
     * @mbggenerated Sun Sep 04 00:03:22 EDT 2016
     */
    public void setEtldate(Date etldate) {
        this.etldate = etldate;
    }

	public BigDecimal getCount() {
		if(count == null)
			return new BigDecimal(1);
		
		return count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}
}